clear all; close all; clc;

%% Libraries
% Specifications Peter's Coke BUG2 Implementation:
% https://www.petercorke.com/RTB/r9/html/Bug2.html
currentFolder = pwd;
addpath(genpath('C:\Users\Eudald\Documents\Git Repos\PeterCork_PathPlanning_Lib\rtb'));
addpath(genpath('C:\Users\Eudald\Documents\Git Repos\PeterCork_PathPlanning_Lib\common'));
addpath(genpath('C:\Users\Eudald\Documents\Git Repos\PeterCork_PathPlanning_Lib\smtb'));
addpath(genpath([currentFolder, '\MAE_Occupancy_Map']));
addpath(genpath([currentFolder, '\lib\Plots']));
addpath(genpath([currentFolder, '\lib\Navigation']));

% Get the screen size
screenSize = get(0, 'ScreenSize');
% Calculate 90% of the screen width and height
width = round(screenSize(3) * 0.9);
height = round(screenSize(4) * 0.8);

% Calculate the left and bottom coordinates to center the figure
left = round((screenSize(3) - width) / 2);
bottom = round((screenSize(4) - height) / 2);

%% Import EG Map
tStart = tic;   
% Generate the Engineering Gateway 3D map
maps = generateEGMap3DBUG();
tEnd = toc(tStart);
disp("Time Elapsed Plotting EG Map: " + num2str(tEnd))

% Hold the current figure to allow overlaying additional plots
figureHandle = findobj('Type', 'Figure', 'Name', '3D Trajectory MAE UCI');
set(figureHandle, 'Position', [left, bottom, width, height]);
if isempty(figureHandle)
    error('The figure generated by generateEGMap3DBUG does not exist. Ensure the function has executed correctly.');
end

%% Initial Parameters:
scenario = 6;
switch scenario
    % Case BUG2 same floor Target
    case 1
        startHeight = 0;                       % 0 - 2nd Floor , 100 - 3rd Floor , 200 - 4th Floor 
        startPoint  = [15, 144, startHeight];  % X, Y: define the start point
        goalHeight = 0;                       % 0 - 2nd Floor , 100 - 3rd Floor , 200 - 4th Floor
        goalPoint  = [85, 312, goalHeight];   % X, Y: define the goal point
    % Case EExit found earlier than projected target
    case 2
        startHeight = 0;                 
        startPoint  = [15, 144, startHeight];  
        goalHeight = 0; % Target Reached
        goalPoint  = [80, 25, goalHeight];   
    case 3
        startHeight = 0;                 
        startPoint  = [15, 144, startHeight];  
        goalHeight = 200; % Target Not Reached
        goalPoint  = [48, 250, goalHeight];   
    case 4
        startHeight = 0;                 
        startPoint  = [15, 144, startHeight];  
        goalHeight = 100;               % 0 - 2nd Floor , 100 - 3rd Floor , 200 - 4th Floor
        goalPoint  = [85, 165, goalHeight];   
    case 5
        startHeight = 0;                 
        startPoint  = [15, 144, startHeight];  
        goalHeight = 200;               
        goalPoint  = [85, 165, goalHeight];   
    case 6
        startHeight = 0; 
        startPoint  = [45, 28, startHeight];  %80, 74
        goalHeight = 200;               
        goalPoint  = [85, 165, goalHeight];
    case 7
        startHeight = 100; 
        startPoint  = [82, 74, startHeight];  
        goalHeight = 0;               
        goalPoint  = [85, 165, goalHeight];
    case 8
        startHeight = 0; 
        startPoint  = [84, 31, startHeight];  
        goalHeight = 200;               
        goalPoint  = [85, 165, goalHeight];
    case 9
        startHeight = 0; 
        startPoint  = [92, 107, startHeight];  
        goalHeight = 200;               
        goalPoint  = [85, 165, goalHeight];
    case 10
        startHeight = 0; 
        startPoint  = [96, 165, startHeight];  
        goalHeight = 200;               
        goalPoint  = [85, 165, goalHeight];
    case 11
        startHeight = 0; 
        startPoint  = [83, 281, startHeight];  
        goalHeight = 200;               
        goalPoint  = [82, 300, goalHeight]; 
    case 12
        startHeight = 0; 
        startPoint  = [43, 120, startHeight];  
        goalHeight = 200;               
        goalPoint  = [82, 300, goalHeight];
    case 13
        startHeight = 100; 
        startPoint  = [97, 164, startHeight];  
        goalHeight = 100;               
        goalPoint  = [88, 164, goalHeight];
    case 14
        startHeight = 100; 
        startPoint  = [53, 260, startHeight];  
        goalHeight = 0;               
        goalPoint  = [90, 55, goalHeight];
    case 15
        startHeight = 0; 
        startPoint  = [80, 350, startHeight];  
        goalHeight = 0;               
        goalPoint  = [90, 55, goalHeight];
    case 16
        startHeight = 100; 
        startPoint  = [53, 246, startHeight];  
        goalHeight = 0;               
        goalPoint  = [31, 153, goalHeight];
    case 17
        startHeight = 100; 
        startPoint  = [57, 255, startHeight];  
        goalHeight = 200;               
        goalPoint  = [84, 37, goalHeight];
    case 28 % Iter 241
        startHeight = 200; 
        startPoint  = [85, 351, startHeight];  
        goalHeight = 0;               
        goalPoint  = [78, 74, goalHeight];
    case 29 % Iter 204
        startHeight = 100; 
        startPoint  = [89, 165, startHeight];  
        goalHeight = 200;               
        goalPoint  = [82, 10, goalHeight];
    case 30 % Iter 139
        startHeight = 0; 
        startPoint  = [93, 57, startHeight];  
        goalHeight = 200;               
        goalPoint  = [85, 162, goalHeight];
end

visionRadius = 30; % 30
visionAngle = 170; %170

%% Exploration algorithm selection:
ifRandom = 1;

%% Compute & Display the 3D m-line
load('MAE_Occupancy_Map/EG-2Floor_indoor_polygon_MC_Simulation.mat');
load('MAE_Occupancy_Map/EG-2Floor_Hole1_indoor_polygon_MC_Simulation.mat');
load('MAE_Occupancy_Map/EG-2Floor_Hole2_indoor_polygon_MC_Simulation.mat');
load('MAE_Occupancy_Map/EG-2Floor_Hole3_indoor_polygon_MC_Simulation.mat');
load('MAE_Occupancy_Map/EG-3Floor_indoor_polygon_MC_Simulation.mat');
load('MAE_Occupancy_Map/EG-4Floor_indoor_polygon_MC_Simulation.mat');
% Apply translation to the third floor polygon
thirdFloorPolygon = EG_3Floor_indoor_polygon_MC_Simulation(:, [2, 1]);
thirdFloorPolygon(:, 1) = thirdFloorPolygon(:, 1) + 39;  % Add 36 to x-coordinates
% Apply translation to the third floor polygon
fourthFloorPolygon = EG_4Floor_indoor_polygon_MC_Simulation(:, [2, 1]);
fourthFloorPolygon(:, 1) = fourthFloorPolygon(:, 1) + 37;  % Add 36 to x-coordinates
% Swap x and y coordinates for all polygons
secondFloorPolygon = EG_2Floor_indoor_polygon_MC_Simulation(:, [2, 1]);
holes = {
    EG_2Floor_Hole1_indoor_polygon_MC_Simulation(:, [2, 1]),
    EG_2Floor_Hole2_indoor_polygon_MC_Simulation(:, [2, 1]),
    EG_2Floor_Hole3_indoor_polygon_MC_Simulation(:, [2, 1])
};
% Combine polygons into a cell array
polygons = {
    {0, secondFloorPolygon, holes},
    {100, thirdFloorPolygon},
    {200, fourthFloorPolygon}
};
colors = [1 0.4 0.4; 1 0.6 0.6; 1 0.8 0.8]; % Different shades of red for each floor

        
figure(figureHandle);
hold on;
for i = 1:length(polygons)
        floorHeight = polygons{i}{1};
        polygon = polygons{i}{2};
        
        % Create a slightly elevated plane for better visibility
        z = ones(size(polygon, 1), 1) * (floorHeight);
        
        % Plot the polygon as a filled area
%         fill3(polygon(:,1), polygon(:,2), z, colors(i,:), 'FaceAlpha', 0.5);
        
        % Plot the polygon outline
%         plot3(polygon(:,1), polygon(:,2), z, 'k-', 'LineWidth', 2);
        
        % Plot holes for 2nd floor
        if i == 1
            for j = 1:length(holes)
                hole = holes{j};
                z_hole = zeros(size(hole, 1), 1) + floorHeight +0.1;
%                 fill3(hole(:,1), hole(:,2), z_hole, 'w-', 'LineWidth', 3);
            end
        end
    end

mLine3D  = homline(startPoint (1), startPoint (2), goalPoint(1), goalPoint(2)); % Calculate the homogeneous line representation of the m-line
mLine3D  = mLine3D  / norm(mLine3D (1:2)); % Normalize the line

% Get the current axis limits
axisLimits = axis;
xMin = axisLimits(1); xMax = axisLimits(2);
yMin = axisLimits(3); yMax = axisLimits(4);

% Plot 3D m-line
figure(figureHandle); % Bring the existing figure to the foreground
hold on;

% 2D and 3D M-Line representation
if startHeight == goalHeight 
    % If start and goal are on the same floor
    if mLine3D (2) == 0
        % If the line is vertical (infinite slope)
        plot3([startPoint(1) startPoint(1)], [yMin yMax], [startHeight goalHeight], '--', 'Color', '#696969','LineWidth',2);
    else
        % For non-vertical lines
        x = [xMin xMax]';
        y = -[x [1;1]] * [mLine3D(1); mLine3D(3)] / mLine3D(2);
        plot3(x, y, [goalHeight; goalHeight], '--', 'Color', '#696969', 'Linewidth',2);
        axis equal
    end
else
    % If start and goal are on different floors
    x_proj = linspace(startPoint(1), goalPoint(1), 100);
    y_proj = linspace(startPoint(2), goalPoint(2), 100);
    z_proj = startHeight * ones(size(x_proj));

    x = [xMin xMax]';
    y = -[x [1;1]] * [mLine3D(1); mLine3D(3)] / mLine3D(2);

    % 1. Plot the horizontal projection on the start level
    plot3(x, y, [startHeight; startHeight], '-.', 'Color', '#A0A0A0', 'Linewidth', 2, 'DisplayName', 'Horizontal Projection');

    % 2. Plot the 3D m-line from start to goal
    zLine = linspace(startHeight, goalHeight, 100);
    plot3(x_proj, y_proj, zLine, '-', 'Color', '#696969', 'linewidth', 2, 'DisplayName', '3D m-line');

    % 3. Plot the vertical line from (goal_x, goal_y, start_z) to (goal_x, goal_y, goal_z)
    plot3([goalPoint(1), goalPoint(1)], [goalPoint(2), goalPoint(2)], [startHeight, goalHeight], '-.', 'Color', '#696969', 'LineWidth', 2, 'DisplayName', 'Vertical Line');
end

% Plot Initial Position on the 3D plot:
plot3(startPoint (1), startPoint (2), startHeight, 'ko', 'MarkerSize', 6, 'MarkerEdgeColor', 'k', 'MarkerFaceColor', 'g');
% Plot the Final Position on the 3D Plot:
plot3(goalPoint(1), goalPoint(2), goalHeight, 'p', 'MarkerSize', 8, 'MarkerFaceColor', 'r', 'MarkerEdgeColor', 'k');

%% 3D D* Lite Algorithm Implementation:
tStart = tic;
total_path = [];
trajectory_length = 0;

while true
    % CASE 1: Same Floor Navigation - Direct to Goal
    if startHeight == goalHeight
        switch startHeight
            case 0
                ds = DstarLite_ES(maps.grid.floor2, 'visionRadius', 2, 'visionAngle', 170);
            case 100
                ds = DstarLite_ES(maps.grid.floor3, 'visionRadius', 2, 'visionAngle', 170);
            case 200
                ds = DstarLite_ES(maps.grid.floor4, 'visionRadius', 2, 'visionAngle', 170);
        end
        
        pause(1);
        fig = figure;
        set(fig, 'Position', [left, bottom, width, height]);
        
        % Direct navigation to 3D goal (ignore all emergency features)
        [path, goalReached] = ds.query(startPoint, goalPoint, 'animate', true);
        
        total_path = vertcat(total_path, path);
        diff_path = diff(path);
        step_distances = sqrt(sum(diff_path.^2, 2));
        dstar_path_length_cells = length(path);
        dstar_path_length_meters = sum(step_distances)/4;
        trajectory_length = trajectory_length + dstar_path_length_meters;
        fprintf('D* Lite trajectory length (same floor): %.2f units.\n', dstar_path_length_meters);
    
        if ~isempty(path)
            figure(figureHandle);
            hold on;
            switch startHeight
                case 0
                    plot3(path(:,1), path(:,2), ones(size(path,1), 1)*0, 'b-', 'LineWidth', 2);
                case 100
                    plot3(path(:,1), path(:,2), ones(size(path,1), 1)*100, 'b-', 'LineWidth', 2);
                case 200
                    plot3(path(:,1), path(:,2), ones(size(path,1), 1)*200, 'b-', 'LineWidth', 2);
            end
        end
        
        if goalReached
            disp("Target found!")
            tEnd = toc(tStart);
            disp("Time Elapsed to implement the 3D D*-Lite algorithm: " + num2str(tEnd))
            break;
        else
            disp("Robot is trapped, couldn't find path to target.")
            tEnd = toc(tStart);
            disp("Time Elapsed to implement the 3D Bug algorithm: " + num2str(tEnd))
            break;
        end
    
    % CASE 2: Different Floor Navigation - Multi-floor with emergency stairs
    else 
        if ifRandom
            disp("Random trajectory exploration for emergency stairs");

            switch startHeight
                case 0
                    randomExplorer = randomPathEmergencyStairsExploration(maps.grid.floor2, ...
                        'visionRadius', visionRadius, 'visionAngle', visionAngle, ...
                        'stepSize', 1);
                    randomExplorer.setExitCells([maps.emergencyStairs.floor2(1,:)', maps.emergencyStairs.floor2(2,:)']);
                case 100
                    randomExplorer = randomPathEmergencyStairsExploration(maps.grid.floor3, ...
                        'visionRadius', visionRadius, 'visionAngle', visionAngle, ...
                        'stepSize', 1);
                    randomExplorer.setExitCells([maps.emergencyStairs.floor3(1,:)', maps.emergencyStairs.floor3(2,:)']);
                case 200
                    randomExplorer = randomPathEmergencyStairsExploration(maps.grid.floor4, ...
                        'visionRadius', visionRadius, 'visionAngle', visionAngle, ...
                        'stepSize', 1);
                    randomExplorer.setExitCells([maps.emergencyStairs.floor4(1,:)', maps.emergencyStairs.floor4(2,:)']);
            end
            
            % Create figure for visualization
            fig = figure;
            set(fig, 'Position', [left, bottom, width, height]);
            
            % Run random trajectory exploration
            [path, goalReached, exitStairsNumber] = randomExplorer.query(startPoint, goalPoint, ...
                'animate', true, 'maxTime', 300, 'maxSteps', 5000);
            
            total_path = vertcat(total_path, path);
            
            if ~isempty(path)
                % Calculate trajectory length
                diff_path = diff(path);
                step_distances = sqrt(sum(diff_path.^2, 2));
                random_path_length_cells = length(path);
                random_path_length_meters = sum(step_distances)/4;
                trajectory_length = trajectory_length + random_path_length_meters;
                fprintf('Random trajectory length: %.2f units.\n', random_path_length_meters);
                
                % Plot path on 3D figure
                figure(figureHandle);
                hold on;
                switch startHeight
                    case 0
                        plot3(path(:,1), path(:,2), ones(size(path,1), 1)*0, 'b-', 'LineWidth', 2);
                    case 100
                        plot3(path(:,1), path(:,2), ones(size(path,1), 1)*100, 'b-', 'LineWidth', 2);
                    case 200
                        plot3(path(:,1), path(:,2), ones(size(path,1), 1)*200, 'b-', 'LineWidth', 2);
                    otherwise
                        hold off; % Release the hold
                end
            end
            
            % Important, organize exitStairsNumber such as the emergency exits
            % that go across all floors (in the generateEGMap3DBUG function)
            if exitStairsNumber == 1 || exitStairsNumber == 2 || exitStairsNumber == 3
                startHeight = goalHeight;
            end
    
            switch startHeight
                case 0
                    if exitStairsNumber > 0 && exitStairsNumber <= size(maps.emergencyStairs.floor2, 2)
                        startPoint = [maps.emergencyStairs.floor2(:, exitStairsNumber)', startHeight];
                    else
                        error("Invalid exitStairsNumber: %d. Ensure emergency stairs logic is correct.", exitStairsNumber);
                    end
                case 100
                    if exitStairsNumber > 0 && exitStairsNumber <= size(maps.emergencyStairs.floor3, 2)
                        startPoint = [maps.emergencyStairs.floor3(:, exitStairsNumber)', startHeight];
                    else
                        error("Invalid exitStairsNumber: %d. Ensure emergency stairs logic is correct.", exitStairsNumber);
                    end
                case 200
                    if exitStairsNumber > 0 && exitStairsNumber <= size(maps.emergencyStairs.floor4, 2)
                        startPoint = [maps.emergencyStairs.floor4(:, exitStairsNumber)', startHeight];
                    else
                        error("Invalid exitStairsNumber: %d. Ensure emergency stairs logic is correct.", exitStairsNumber);
                    end
            end
        end
    end
end

% Calculate total trajectory metrics
total_path_length_cells = random_path_length_cells + dstar_path_length_cells;
total_path_length_meters = random_path_length_meters + dstar_path_length_meters;

% Hold the current figure to allow overlaying additional plots
figureHandle = findobj('Type', 'Figure', 'Name', '3D Trajectory MAE UCI');
if isempty(figureHandle)
    error('The figure generated by generateEGMap3DBUG does not exist. Ensure the function has executed correctly.');
end

% Apply axis label modifications to the current figure
figure(gcf);  % Make sure we're working with the current figure
ax = gca;
xlabel('$X,\, \mathrm{m}$', 'Interpreter', 'latex');
ylabel('$Y,\, \mathrm{m}$', 'Interpreter', 'latex');
zlabel('', 'Interpreter', 'latex')
title('Iter 139 r=30', 'Interpreter', 'latex');
axis equal;
grid on;

% Convert pixel ticks to meter values for x-axis
xticks_pixels = ax.XTick;
xticks_meters = xticks_pixels * 0.25;
xticks(xticks_pixels);
xticklabels(arrayfun(@(x) sprintf('%.1f', x), xticks_meters, 'UniformOutput', false));

% Set y-axis ticks every 10 meters
ylim([0, 365]);  % Set y-axis limits
yticks_meters = 0:10:365;  % Create ticks every 10 meters
yticks_pixels = yticks_meters / 0.25;  % Convert meters to pixels
yticks(yticks_pixels);
yticklabels(arrayfun(@(x) sprintf('%.1f', x), yticks_meters, 'UniformOutput', false));

%% COMPREHENSIVE TRAJECTORY SUMMARY
fprintf('\n');
fprintf('=====================================\n');
fprintf('      TRAJECTORY SUMMARY REPORT      \n');
fprintf('=====================================\n');
fprintf('\n');

% Random Path Summary
if random_path_length_cells > 0
    fprintf('🔍 RANDOM EXPLORATION PHASE:\n');
    fprintf('   • Path length (cells):  %d cells\n', random_path_length_cells);
    fprintf('   • Path length (meters): %.2f m\n', random_path_length_meters);
    fprintf('   • Average step size:    %.3f m/cell\n', random_path_length_meters/random_path_length_cells);
    fprintf('\n');
else
    fprintf('🔍 RANDOM EXPLORATION PHASE: Not executed\n\n');
end

% D* Lite Path Summary
if dstar_path_length_cells > 0
    fprintf('🎯 D* LITE NAVIGATION PHASE:\n');
    fprintf('   • Path length (cells):  %d cells\n', dstar_path_length_cells);
    fprintf('   • Path length (meters): %.2f m\n', dstar_path_length_meters);
    fprintf('   • Average step size:    %.3f m/cell\n', dstar_path_length_meters/dstar_path_length_cells);
    fprintf('\n');
else
    fprintf('🎯 D* LITE NAVIGATION PHASE: Not executed\n\n');
end

% Total Summary
fprintf('📊 TOTAL TRAJECTORY:\n');
fprintf('   • Total cells traveled:  %d cells\n', total_path_length_cells);
fprintf('   • Total distance:        %.2f m\n', total_path_length_meters);
fprintf('\n');

% Performance Breakdown
if random_path_length_cells > 0 && dstar_path_length_cells > 0
    random_percentage = (random_path_length_meters / total_path_length_meters) * 100;
    dstar_percentage = (dstar_path_length_meters / total_path_length_meters) * 100;
    
    fprintf('📈 PERFORMANCE BREAKDOWN:\n');
    fprintf('   • Random exploration:    %.1f%% of total distance\n', random_percentage);
    fprintf('   • D* Lite navigation:    %.1f%% of total distance\n', dstar_percentage);
    fprintf('\n');
end

% Scenario Information
fprintf('🏢 SCENARIO DETAILS:\n');
fprintf('   • Start floor:           %d\n', startHeight);
fprintf('   • Goal floor:            %d\n', goalHeight);
fprintf('   • Vision radius:         %d m\n', visionRadius);
fprintf('   • Vision angle:          %d°\n', visionAngle);
fprintf('\n');

% Time Performance
fprintf('⏱️  EXECUTION TIME:\n');
fprintf('   • Total execution time:  %.2f seconds\n', toc(tStart));
fprintf('\n');

fprintf('=====================================\n');
fprintf('           END OF REPORT             \n');
fprintf('=====================================\n');

% Legacy output for compatibility
disp(['Length path (cells): ' num2str(total_path_length_cells)])
disp(['Length path (meters): ' num2str(total_path_length_meters)])